<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mana.Launcher</RootNamespace>
    <AssemblyName>Install-mana</AssemblyName>
    <Version>1.0.0</Version>
    <InformationalVersion>1.00</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>mana as setting keyboard layout</Product>
    <Company>Applet LLC</Company>
    <Description>mana as setting keyboard layout</Description>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <Platforms>x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
